default_context:
  project_name: 'portfolioquick'
  project_slug: 'portfolioquick'
  domain_main: 'andrijajovanovic.tk'
  domain_staging: 'stag.andrijajovanovic.tk'
  docker_swarm_stack_name_main: 'andrijajovanovic-tk'
  docker_swarm_stack_name_staging: 'stag-andrijajovanovic-tk'
  secret_key: 'mojasoba'
  first_superuser: 'admin@andrijajovanovic.tk'
  first_superuser_password: 'mojasoba'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.andrijajovanovic.tk", "https://stag.andrijajovanovic.tk", "https://andrijajovanovic.tk", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'smtp.gmail.com'
  smtp_user: 'andrijajovanovic001@gmail.com'
  smtp_password: 'mojasobasobica'
  smtp_emails_from_email: 'info@andrijajovanovic.tk'
  postgres_password: 'mojasoba'
  pgadmin_default_user: 'admin@andrijajovanovic.tk'
  pgadmin_default_user_password: 'mojasoba'
  traefik_constraint_tag: 'andrijajovanovic.tk'
  traefik_constraint_tag_staging: 'stag.andrijajovanovic.tk'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:mojasoba'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
